// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rules} from '../models';
import {profiles} from '../models';
import {monitor} from '../models';
import {logging} from '../models';
import {stats} from '../models';

export function ActivateProfile(arg1:string):Promise<void>;

export function AddRule(arg1:rules.Rule):Promise<void>;

export function ApplyRule(arg1:rules.Rule):Promise<void>;

export function ClearActiveProcesses():Promise<void>;

export function ClearMonitoringEvents():Promise<void>;

export function ClearProcessTraffic():Promise<void>;

export function CreateProfile(arg1:profiles.Profile):Promise<void>;

export function DisablePrompts():Promise<void>;

export function EnablePrompts():Promise<void>;

export function GetActiveProcesses():Promise<Array<monitor.ConnectionEvent>>;

export function GetLogs(arg1:string):Promise<Array<logging.Event>>;

export function GetMonitoringEvents():Promise<Array<monitor.ConnectionEventLog>>;

export function GetMonitoringStatus():Promise<boolean>;

export function GetProcessTraffic():Promise<Array<monitor.ProcessTraffic>>;

export function GetStats():Promise<Record<string, number>>;

export function GetStatsFiltered(arg1:stats.Filter):Promise<Array<stats.ConnectionStat>>;

export function ListProfiles():Promise<Array<profiles.Profile>>;

export function ListRules():Promise<Array<rules.Rule>>;

export function PromptsEnabled():Promise<boolean>;

export function RemoveRule(arg1:string):Promise<void>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;
