// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rules} from '../models';
import {profiles} from '../models';
import {logging} from '../models';
import {stats} from '../models';

export function ActivateProfile(arg1:string):Promise<void>;

export function AddRule(arg1:rules.Rule):Promise<void>;

export function ApplyRule(arg1:rules.Rule):Promise<void>;

export function CreateProfile(arg1:profiles.Profile):Promise<void>;

export function GetLogs(arg1:string):Promise<Array<logging.Event>>;

export function GetStats():Promise<Record<string, number>>;

export function GetStatsFiltered(arg1:stats.Filter):Promise<Array<stats.ConnectionStat>>;

export function ListProfiles():Promise<Array<profiles.Profile>>;

export function ListRules():Promise<Array<rules.Rule>>;

export function RemoveRule(arg1:string):Promise<void>;
